name: website
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Volta
        uses: volta-cli/action@v4

      - name: Build website
        run: |
          cd website
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/build
          clean: true
